api:
  api_key: "TWITTER_API_KEY"
  api_key_secret: "TWITTER_API_SECRET_KEY"
  access_token: "TWITTER_ACCESS_TOKEN"
  access_token_secret: "TWITTER_ACCESS_TOKEN_SECRET"
  bearer_token: "TWITTER_BEARER_TOKEN"